/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "usart.h"
#include "timer.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "event_groups.h"

#define USART3_READY_EVT (1 << 0)

typedef struct{
	int16_t right_motor_speed;
	int16_t left_motor_speed;
}motor_param_t;

typedef enum{
	SPEED = 0xA1,
	DISTANCE =0xA2,
}msg_t;

static volatile QueueHandle_t xFlysky;
static volatile QueueHandle_t xParamToSend;
static volatile EventGroupHandle_t xUsart3Ready;

uint32_t cnt1;
uint32_t cnt2;
uint32_t cnt3;
uint32_t value[9];
uint8_t cnt;
uint8_t msg[5];

motor_param_t dc_driver;

void vTask(void *pvParameters)
{
	uint32_t* pulPtr = (uint32_t* )pvParameters;

	while(1)
	{
		(*pulPtr)++;

		vTaskDelay(pdMS_TO_TICKS(1000));
	}
}

void vParseTask(void *pvParameters)
{
	uint32_t param[9];
	int16_t right_motor_speed, left_motor_speed, speed, turn;

	while(1)
	{
		xQueueReceive(xFlysky, &param, portMAX_DELAY);

		turn = ((int16_t)param[0] - 5940) / 20;
		speed = ((int16_t)param[1] - 5940) / 20;

		if(speed > 0 && turn > 0)
		{
			right_motor_speed = speed - turn;
			left_motor_speed = speed;
		}
		else if(speed > 0 && turn < 0)
		{
			right_motor_speed = speed;
			left_motor_speed = speed + turn;
		}
		else if(speed < 0 && turn > 0)
		{
			right_motor_speed = speed + turn;
			left_motor_speed = speed;
		}
		else if(speed < 0 && turn < 0)
		{
			right_motor_speed = speed;
			left_motor_speed = speed - turn;
		}
		else
		{
			right_motor_speed = speed;
			left_motor_speed = speed;
		}

		if(abs(right_motor_speed - dc_driver.right_motor_speed) > 10 || abs(left_motor_speed - dc_driver.left_motor_speed) > 10)
		{
			dc_driver.right_motor_speed = right_motor_speed;
			dc_driver.left_motor_speed = left_motor_speed;

			uint8_t rm1 = (right_motor_speed >> 8) & 0xFF;
			uint8_t rm2 = right_motor_speed & 0xFF;

			uint8_t lm1 = (left_motor_speed >> 8) & 0xFF;
			uint8_t lm2 = left_motor_speed & 0xFF;

			msg[0] = SPEED;
			msg[1] = rm1;
			msg[2] = rm2;
			msg[3] = lm1;
			msg[4] = lm2;

			xEventGroupWaitBits(xUsart3Ready, USART3_READY_EVT, pdTRUE, pdFALSE, pdMS_TO_TICKS(100));

			Usart3TransmitDMA((uint32_t)msg);

			//halUsart3SendCommand(SPEED, right_motor_speed, left_motor_speed, 100);
		}
	}
}

void vUsart3TxCallback(void)
{
	BaseType_t xHigherTaskWoken = pdFALSE;

	if(xEventGroupSetBitsFromISR(xUsart3Ready, USART3_READY_EVT, &xHigherTaskWoken) != pdPASS) cnt3++;

	portYIELD_FROM_ISR(xHigherTaskWoken);
}

void vTimerCallback(void)
{
	uint32_t v = Tim3GetValue();
	BaseType_t xHigherTaskWoken = pdFALSE;

	if(v > 8000) cnt = 8;

	value[cnt] = v;

	cnt++;

	if(cnt > 8)
	{
		if(xQueueSendFromISR(xFlysky, &value, &xHigherTaskWoken) != pdPASS) cnt2++;

		cnt = 0;
	}

	portYIELD_FROM_ISR(xHigherTaskWoken);
}


int main(void)
{
 	halUsart2Init();
 	Usart3DMAInit();
 	Tim3InitImputCaptureMode();

 	Tim3RegisterCallback(vTimerCallback);
 	Usart3RegisterCallback(vUsart3TxCallback);

 	xFlysky = xQueueCreate(2, sizeof(value));
 	xUsart3Ready = xEventGroupCreate();
 	xEventGroupSetBits(xUsart3Ready, USART3_READY_EVT);

	xTaskCreate(vTask, "Task1", 512, &cnt1, 1, NULL);
	xTaskCreate(vParseTask, "ParseTask", 512, &dc_driver, 1, NULL);

	halUsart2Send("System ready\r\n", 100);

	Tim3Start();

	vTaskStartScheduler();

	while(1)
	{
	}
}
