/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "usart.h"
#include "timer.h"

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"

typedef struct{
	int16_t right_motor_speed;
	int16_t left_motor_speed;
}motor_param_t;

typedef enum{
	SPEED = 0xA1,
	DISTANCE =0xA2,
}msg_t;

static volatile QueueHandle_t xFlysky;
static volatile QueueHandle_t xParamToSend;

uint32_t cnt1;
uint32_t cnt2;
uint32_t value[9];
uint8_t cnt;

motor_param_t dc_driver;

void vTask(void *pvParameters)
{
	uint32_t* pulPtr = (uint32_t* )pvParameters;

	while(1)
	{
		(*pulPtr)++;

		//halUsart3SendCommand(0, 100, 10);

		vTaskDelay(pdMS_TO_TICKS(1000));
	}
}

void vParseTask(void *pvParameters)
{
	uint32_t param[9];
	int16_t right_motor_speed, left_motor_speed, speed, turn;

	while(1)
	{
		xQueueReceive(xFlysky, &param, portMAX_DELAY);

		turn = ((int16_t)param[0] - 5940) / 20;
		speed = ((int16_t)param[1] - 5940) / 20;

		if(speed > 0 && turn > 0)
		{
			right_motor_speed = speed - turn;
			left_motor_speed = speed;
		}
		else if(speed > 0 && turn < 0)
		{
			right_motor_speed = speed;
			left_motor_speed = speed + turn;
		}
		else if(speed < 0 && turn > 0)
		{
			right_motor_speed = speed + turn;
			left_motor_speed = speed;
		}
		else if(speed < 0 && turn < 0)
		{
			right_motor_speed = speed;
			left_motor_speed = speed - turn;
		}
		else
		{
			right_motor_speed = speed;
			left_motor_speed = speed;
		}

		if(abs(right_motor_speed - dc_driver.right_motor_speed) > 10 || abs(left_motor_speed - dc_driver.left_motor_speed) > 10)
		{
			dc_driver.right_motor_speed = right_motor_speed;
			dc_driver.left_motor_speed = left_motor_speed;

			halUsart3SendCommand(SPEED, right_motor_speed, left_motor_speed, 100);
		}
	}
}

void vTimerCallback(void)
{
	uint32_t v = halTim3GetValue();
	BaseType_t xHigherTaskWoken = pdFALSE;

	if(v > 8000) cnt = 8;

	value[cnt] = v;

	cnt++;

	if(cnt > 8)
	{
		if(xQueueSendFromISR(xFlysky, &value, &xHigherTaskWoken) != pdPASS) cnt2++;

		cnt = 0;
	}

	portYIELD_FROM_ISR(xHigherTaskWoken);
}


int main(void)
{
 	halUsart2Init();
 	halUsart3Init();
 	halTim3InitImputCaptureMode();

 	halTim3RegisterCallback(vTimerCallback);

 	xFlysky = xQueueCreate(2, sizeof(value));

	xTaskCreate(vTask, "Task1", 512, &cnt1, 1, NULL);
	xTaskCreate(vParseTask, "ParseTask", 512, &dc_driver, 1, NULL);

	halUsart2Send("System ready\r\n", 100);
	halUsart3Put(85, 100);

	halTim3Start();

	vTaskStartScheduler();

	while(1)
	{
	}
}
